services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: template_rbac_database
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3300:3306"
    volumes:
      - ./data:/var/lib/mysql

#volumes:
#  mysql_data:
