spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/template_rbac_database
    username: root
    password: rootPassword

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allow-credentials: true
  max-age: 3600

jwt:
  secret: super-secret-key-super-secret-key
  secret-refresh: super-secret-key-super-refresh-key
  expiration: 3600
  expiration-refresh: 604800
  issuer: unknown

logging:
  level:
    org.springframework.security: DEBUG
    com.pornput.rbactemplate: DEBUG
